program: train_model_wandb_2.py
method: random
metric:
  name: train_loss
  goal: minimize
early_terminate:
  type: hyperband
  min_iter: 3
parameters:
  Project:
    values: 
      - ALR_VAME_1
    distribution: categorical
  project_path:
    values: 
      - /content/VAME_files/ALR_VAME_1-Sep15-2023
    distribution: categorical
  model_name:
    values: 
      - VAME
    distribution: categorical
  pretrained_model:
    values: 
      - null
    distribution: categorical
  pretrained_weights:
    values: 
      - false
    distribution: categorical
  num_features:
    value: 28
    distribution: constant
  batch_size:
    min: 256
    max: 2048
    distribution: int_uniform
  max_epochs:
    min: 250
    max: 500
    distribution: int_uniform
  model_snapshot:
    value: 15
    distribution: constant
  model_convergence:
    value: 50
    distribution: constant
  transition_function:
    values: 
      - "GRU"
    distribution: categorical
  beta:
    value: 1
    distribution: constant
  beta_norm:
    values: 
      - false
    distribution: categorical
  zdims:
    min: 15
    max: 60
    distribution: int_uniform
  learning_rate:
    min: 0.0001
    max: 0.01
    distribution: log_uniform_values
  time_window:
    min: 30
    max: 120
    distribution: int_uniform
  prediction_decoder:
    value: 1
    distribution: constant
  prediction_steps:
    min: 15
    max: 30
    distribution: int_uniform
  noise:
    values: 
      - true
      - false
    distribution: categorical
  scheduler:
    value: 1
    distribution: constant
  scheduler_step_size:
    min: 50
    max: 300
    distribution: int_uniform
  scheduler_gamma:
    min: 0.1
    max: 0.9
    distribution: uniform
  scheduler_threshold:
    min: 0.0001
    max: 0.1
    distribution: uniform
  softplus:
    values: [true, false]
  hidden_layer_size_1:
    value: 256
    distribution: constant
  hidden_layer_size_2:
    value: 256
    distribution: constant
  dropout_encoder:
    values:
      - 0
      - 1
    distribution: categorical
  hidden_size_rec:
    value: 256
    distribution: constant
  dropout_rec:
    values:
      - 0
      - 1
    distribution: categorical
  n_layers:
    min: 1
    max: 2
    distribution: int_uniform
  hidden_size_pred:
    value: 256
    distribution: constant
  dropout_pred:
    values:
      - 0
      - 1
    distribution: categorical
  mse_reconstruction_reduction:
    values: 
      - sum
    distribution: categorical
  mse_prediction_reduction:
    values: 
      - sum
    distribution: categorical
  kmeans_loss:
    min: 30
    max: 45
    distribution: int_uniform
  kmeans_lambda:
    min: 0.1
    max: 0.2
    distribution: uniform
  anneal_function:
    values: 
      - linear
      - sigmoid
    distribution: categorical
  kl_start:
    value: 2
    distribution: constant
  annealtime:
    value: 4
    distribution: constant
  legacy:
    values: 
      - false
    distribution: categorical